// src/main.jsx
//
// This is the entry point of your React app — the very first JavaScript file
// the browser runs. It mounts your App component into the HTML page and
// registers the service worker.

import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import './index.css';
import App from './App.jsx';

// Mount the React app into the <div id="root"> element in index.html.
// StrictMode is a development tool — it runs each component twice to help
// catch bugs early. It has no effect in the production build.
createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>,
);

// ── Service Worker Registration ─────────────────────────────────────────────
//
// What is a service worker?
// A service worker is a JavaScript file that runs in the background, separate
// from your main app. Think of it as a "middleman" that sits between your app
// and the network. When your app asks for a file (like a CSS file or image),
// the service worker can intercept that request and serve a cached copy from
// the user's device instead of downloading it again. This makes the app:
//   - Load faster (reading from device storage is faster than the network)
//   - Work offline (the cached files are available even without internet)
//   - Feel more like a native app
//
// The service worker file itself (/sw.js) is auto-generated by vite-plugin-pwa
// during the build. You don't write it manually.
//
// Why only register in production?
// During development (npm run dev), Vite uses a live-reload server that would
// conflict with service worker caching. So we only register in production
// (after running npm run build) to avoid confusing behavior in development.

if (import.meta.env.PROD && 'serviceWorker' in navigator) {
  // 'serviceWorker' in navigator checks if this browser supports service workers.
  // Old browsers (like IE11) don't, so this prevents a crash on those browsers.

  // We wait until the window has fully loaded before registering the SW.
  // This ensures the service worker setup doesn't compete with the initial
  // page load and slow down the first render.
  window.addEventListener('load', () => {
    navigator.serviceWorker
      .register('/sw.js') // this file is generated by vite-plugin-pwa at build time
      .then((registration) => {
        console.log('[LiveHoops] Service worker registered successfully:', registration.scope);
      })
      .catch((err) => {
        // This can fail if: the sw.js file doesn't exist, the server returns
        // an error, or the browser blocks service workers (e.g. in private mode)
        console.error('[LiveHoops] Service worker registration failed:', err);
      });
  });
}
